#line 1 "e:\\THE_CREATION_STATION\\#Arduino_Workspace\\Irrigation_Controller_V1.0\\src\\settings\\OxygenPumpSettings.h"
#ifndef OXYGENPUMPSETTINGS_H
#define OXYGENPUMPSETTINGS_H

//ALARM FROM 4AM - 5AM
#define OXYGEN_PUMP_ON_HOUR_A1 4
#define OXYGEN_PUMP_OFF_HOUR_A1 5

//ALARM FROM 1PM TO 2PM
#define OXYGEN_PUMP_ON_HOUR_A2 13
#define OXYGEN_PUMP_OFF_HOUR_A2 14

//ALARM FROM
#define OXYGEN_PUMP_ON_HOUR_A3 0
#define OXYGEN_PUMP_OFF_HOUR_A3 0

//ALARM FROM
#define OXYGEN_PUMP_ON_HOUR_A4 0
#define OXYGEN_PUMP_OFF_HOUR_A4 0



#endif