#ifndef OXYGENPUMPSETTINGS_H
#define OXYGENPUMPSETTINGS_H

#define OXYGEN_PUMP_ON_HOUR_A1 5
#define OXYGEN_PUMP_OFF_HOUR_A1 6

#define OXYGEN_PUMP_ON_HOUR_A2 10
#define OXYGEN_PUMP_OFF_HOUR_A2 11

#define OXYGEN_PUMP_ON_HOUR_A3 16
#define OXYGEN_PUMP_OFF_HOUR_A3 17

#define OXYGEN_PUMP_ON_HOUR_A4 21
#define OXYGEN_PUMP_OFF_HOUR_A4 22



#endif