#ifndef OXYGENPUMPSETTINGS_H
#define OXYGENPUMPSETTINGS_H

// INTERVALS
#define OXYGEN_PUMP_INTERVAL_A1 120000
#define OXYGEN_PUMP_INTERVAL_A2 70000
#define OXYGEN_PUMP_INTERVAL_A3 70000

//ALARM #1
#define OXYGEN_PUMP_ON_HOUR_A1 4
#define OXYGEN_PUMP_ON_MINUTE_A1 0
#define OXYGEN_PUMP_OFF_HOUR_A1 4
#define OXYGEN_PUMP_OFF_MINUTE_A1 30

//ALARM #2
#define OXYGEN_PUMP_ON_HOUR_A2 4
#define OXYGEN_PUMP_ON_MINUTE_A2 0
#define OXYGEN_PUMP_OFF_HOUR_A2 4
#define OXYGEN_PUMP_OFF_MINUTE_A2 30

//ALARM #3
#define OXYGEN_PUMP_ON_HOUR_A3 4
#define OXYGEN_PUMP_ON_MINUTE_A3 0
#define OXYGEN_PUMP_OFF_HOUR_A3 4
#define OXYGEN_PUMP_OFF_MINUTE_A3 30



#endif