#ifndef REDLIGHTSETTINGS_H
#define REDLIGHTSETTINGS_H

#define RED_LIGHT_ON_HOUR_A1 5
#define RED_LIGHT_OFF_HOUR_A1 6

#define RED_LIGHT_ON_HOUR_A2 9
#define RED_LIGHT_OFF_HOUR_A2 10

#define RED_LIGHT_ON_HOUR_A3 14
#define RED_LIGHT_OFF_HOUR_A3 15

#define RED_LIGHT_ON_HOUR_A4 18
#define RED_LIGHT_OFF_HOUR_A4 19



#endif