#ifndef REDLIGHTSETTINGS_H
#define REDLIGHTSETTINGS_H

#define RED_LIGHT_ON_HOUR_A1 5
#define RED_LIGHT_OFF_HOUR_A1 6

#define RED_LIGHT_ON_HOUR_A2 10
#define RED_LIGHT_OFF_HOUR_A2 11

#define RED_LIGHT_ON_HOUR_A3 16
#define RED_LIGHT_OFF_HOUR_A3 17

#define RED_LIGHT_ON_HOUR_A4 21
#define RED_LIGHT_OFF_HOUR_A4 22



#endif