#ifndef TESTDEVICESETTINGS_H
#define TESTDEVICESETTINGS_H

#define TEST_DEVICE_ON_HOUR_A1 1
#define TEST_DEVICE_OFF_HOUR_A1 9

#define TEST_DEVICE_ON_HOUR_A2 10
#define TEST_DEVICE_OFF_HOUR_A2 11

#define TEST_DEVICE_ON_HOUR_A3 16
#define TEST_DEVICE_OFF_HOUR_A3 17

#define TEST_DEVICE_ON_HOUR_A4 21
#define TEST_DEVICE_OFF_HOUR_A4 24




#endif