#ifndef TESTDEVICESETTINGS_H
#define TESTDEVICESETTINGS_H

#define TEST_DEVICE_INTERVAL 10000

#define TEST_DEVICE_ON_HOUR_A1 22
#define TEST_DEVICE_ON_MINUTE_A1 45
#define TEST_DEVICE_OFF_HOUR_A1 22
#define TEST_DEVICE_OFF_MINUTE_A1 50

#define TEST_DEVICE_ON_HOUR_A2 21
#define TEST_DEVICE_ON_MINUTE_A2 4
#define TEST_DEVICE_OFF_HOUR_A2 21
#define TEST_DEVICE_OFF_MINUTE_A2 6

#define TEST_DEVICE_ON_HOUR_A3 21
#define TEST_DEVICE_ON_MINUTE_A3 8
#define TEST_DEVICE_OFF_HOUR_A3 21
#define TEST_DEVICE_OFF_MINUTE_A3 10



#endif