#ifndef TESTDEVICESETTINGS_H
#define TESTDEVICESETTINGS_H

//INTERVALS
#define TEST_DEVICE_INTERVAL_A1 120000
#define TEST_DEVICE_INTERVAL_A2 70000
#define TEST_DEVICE_INTERVAL_A3 70000
#define TEST_DEVICE_INTERVAL_A4 70000

//ALARM #1
#define TEST_DEVICE_ON_HOUR_A1 22
#define TEST_DEVICE_ON_MINUTE_A1 45
#define TEST_DEVICE_OFF_HOUR_A1 22
#define TEST_DEVICE_OFF_MINUTE_A1 50

//ALARM #2
#define TEST_DEVICE_ON_HOUR_A2 21
#define TEST_DEVICE_ON_MINUTE_A2 4
#define TEST_DEVICE_OFF_HOUR_A2 21
#define TEST_DEVICE_OFF_MINUTE_A2 6

//ALARM #3
#define TEST_DEVICE_ON_HOUR_A3 21
#define TEST_DEVICE_ON_MINUTE_A3 8
#define TEST_DEVICE_OFF_HOUR_A3 21
#define TEST_DEVICE_OFF_MINUTE_A3 10



#endif