#ifndef WATERPUMPSETTINGS_H
#define WATERPUMPSETTINGS_H

#define WATER_PUMP_INTERVAL 120000

#define WATER_PUMP_ON_HOUR_A1 22
#define WATER_PUMP_ON_MINUTE_A1 41
#define WATER_PUMP_OFF_HOUR_A1 22
#define WATER_PUMP_OFF_MINUTE_A1 45

#define WATER_PUMP_ON_HOUR_A2 22
#define WATER_PUMP_ON_MINUTE_A2 40
#define WATER_PUMP_OFF_HOUR_A2 22
#define WATER_PUMP_OFF_MINUTE_A2 41

#define WATER_PUMP_ON_HOUR_A3 22
#define WATER_PUMP_ON_MINUTE_A3 42
#define WATER_PUMP_OFF_HOUR_A3 22
#define WATER_PUMP_OFF_MINUTE_A3 43

#endif