#ifndef WATERPUMPSETTINGS_H
#define WATERPUMPSETTINGS_H

//INTERVALS
#define WATER_PUMP_INTERVAL_A1 70000
#define WATER_PUMP_INTERVAL_A2 70000
#define WATER_PUMP_INTERVAL_A3 70000

//ALARM #1
#define WATER_PUMP_ON_HOUR_A1 5
#define WATER_PUMP_ON_MINUTE_A1 0
#define WATER_PUMP_OFF_HOUR_A1 5
#define WATER_PUMP_OFF_MINUTE_A1 5

//ALARM #2
#define WATER_PUMP_ON_HOUR_A2 2
#define WATER_PUMP_ON_MINUTE_A2 39
#define WATER_PUMP_OFF_HOUR_A2 2
#define WATER_PUMP_OFF_MINUTE_A2 40

//ALARM #3
#define WATER_PUMP_ON_HOUR_A3 5
#define WATER_PUMP_ON_MINUTE_A3 0
#define WATER_PUMP_OFF_HOUR_A3 5
#define WATER_PUMP_OFF_MINUTE_A3 5

#endif