#ifndef WATERPUMPSETTINGS_H
#define WATERPUMPSETTINGS_H

#define WATER_PUMP_ON_HOUR_A1 5
#define WATER_PUMP_OFF_HOUR_A1 6

#define WATER_PUMP_ON_HOUR_A2 10
#define WATER_PUMP_OFF_HOUR_A2 11

#define WATER_PUMP_ON_HOUR_A3 16
#define WATER_PUMP_OFF_HOUR_A3 17

#define WATER_PUMP_ON_HOUR_A4 21
#define WATER_PUMP_OFF_HOUR_A4 24



#endif