#ifndef WHITELIGHTSETTINGS_H
#define WHITELIGHTSETTINGS_H

//ALARM FROM 6AM - 6AM
#define WHITE_LIGHT_ON_HOUR_A1 6
#define WHITE_LIGHT_OFF_HOUR_A1 9

//ALARM FROM 10AM - 1PM
#define WHITE_LIGHT_ON_HOUR_A2 10
#define WHITE_LIGHT_OFF_HOUR_A2 13

//ALARM FROM 3PM TO 6PM
#define WHITE_LIGHT_ON_HOUR_A3 15
#define WHITE_LIGHT_OFF_HOUR_A3 18

//ALARM FROM 
#define WHITE_LIGHT_ON_HOUR_A4 0
#define WHITE_LIGHT_OFF_HOUR_A4 0



#endif