#ifndef WHITELIGHTSETTINGS_H
#define WHITELIGHTSETTINGS_H

#define WHITE_LIGHT_ON_HOUR_A1 5
#define WHITE_LIGHT_OFF_HOUR_A1 6

#define WHITE_LIGHT_ON_HOUR_A2 10
#define WHITE_LIGHT_OFF_HOUR_A2 11

#define WHITE_LIGHT_ON_HOUR_A3 16
#define WHITE_LIGHT_OFF_HOUR_A3 17

#define WHITE_LIGHT_ON_HOUR_A4 21
#define WHITE_LIGHT_OFF_HOUR_A4 22



#endif